name: Daily Farcaster Post

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  post-to-farcaster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch latest changes
        run: git pull origin main

      - name: Create files if they don't exist
        run: |
          if [ ! -f progress.json ]; then
            echo '{"last_index": -1}' > progress.json
          fi
          if [ ! -f last_hash.json ]; then
            echo '{"hash": null}' > last_hash.json
          fi
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add progress.json last_hash.json

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          NEYNAR_API_KEY: ${{ secrets.NEYNAR_API_KEY }}
          FARCASTER_FID: ${{ secrets.FARCASTER_FID }}
          SIGNER_UUID: ${{ secrets.SIGNER_UUID }}
        run: node daily_thucydides_bot.js

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add progress.json last_hash.json
          git diff --staged --quiet || (git commit -m "Update reading progress" && git push)